# Generated by Django 4.0.6 on 2022-08-03 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesas',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='receitas',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
