# Generated by Django 4.0.6 on 2022-08-05 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacoes', '0002_alter_despesas_valor_alter_receitas_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesas',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
