# Generated by Django 4.0.6 on 2022-08-10 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacoes', '0003_alter_despesas_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesas',
            name='categoria',
            field=models.CharField(choices=[('1', 'Alimentação'), ('2', 'Saúde'), ('3', 'Moradia'), ('4', 'Transporte'), ('5', 'Educação'), ('6', 'Lazer'), ('7', 'Imprevistos'), ('8', 'Outras')], default='Outras', max_length=15),
        ),
    ]
