# Generated by Django 4.0.6 on 2022-08-24 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacoes', '0005_alter_despesas_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receitas',
            name='valor',
            field=models.FloatField(),
        ),
    ]
